// Component category definitions
export const componentCategories = {
  Ratings: [
    "star-rating-basic",
    "star-rating-fractions",
    "upvote-rating-basic",
    "upvote-rating-animated",
    "face-rating-basic",
    "face-rating-gradient",
  ],
  Images: ["image-viewer-basic", "image-viewer-motion", "image-carousel-basic"],
  Products: [
    "price-format-basic",
    "price-format-sale",
    "quantity-input-basic",
    "variant-color-selector-basic",
    "variant-selector-basic",
    "variant-selector-images",
    "variant-selector-multiple",
  ],
  Inputs: ["phone-number-input-basic"],
};

export const blocksCategories = {
  Banners: [
    "banner-01-block",
    "banner-02-block",
    "banner-03-block",
    "banner-04-block",
    "banner-05-block",
    "banner-06-block",
    "banner-07-block",
    "banner-08-block",
    "banner-09-block",
    "banner-10-block",
    "banner-11-block",
    "banner-12-block",
  ],
  ProductCards: [
    "product-card-01-block",
    "product-card-02-block",
    "product-card-03-block",
    "product-card-04-block",
    "product-card-05-block",
    "product-card-06-block",
    "product-card-07-block",
    "product-card-08-block",
    "product-card-09-block",
    "product-card-10-block",
    "product-card-11-block",
    "product-card-12-block",
    "product-card-13-block",
  ],
  ProductVariants: [
    "product-variant-01-block",
    "product-variant-02-block",
    "product-variant-03-block",
    "product-variant-04-block",
    "product-variant-05-block",
  ],
  Reviews: [
    "review-01-block",
    "review-02-block",
    "review-03-block",
    "review-04-block",
    "review-05-block",
    "review-06-block",
    "review-07-block",
    "review-08-block",
    "review-09-block",
    "review-10-block",
  ],
  Carts: ["cart-01-block"],
};
